build: off
environment:
  nodejs_version: "9"
cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm ci
test_script:
  - npm test -- --coverage
