// flow-typed signature: b94373bee89370e4e1b14375b6b9b49e
// flow-typed version: <<STUB>>/flow-types_v1.0.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-types/bin/flow-types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-types/bin/flow-types.js' {
  declare module.exports: $Exports<'flow-types/bin/flow-types'>;
}
declare module 'flow-types/index' {
  declare module.exports: $Exports<'flow-types'>;
}
declare module 'flow-types/index.js' {
  declare module.exports: $Exports<'flow-types'>;
}
