// flow-typed signature: 2400c0d5c5afcd70dd28635390a7c85b
// flow-typed version: <<STUB>>/is-retry-allowed_v^1.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-retry-allowed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-retry-allowed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-retry-allowed/index' {
  declare module.exports: $Exports<'is-retry-allowed'>;
}
declare module 'is-retry-allowed/index.js' {
  declare module.exports: $Exports<'is-retry-allowed'>;
}
