// flow-typed signature: c5d8854065bb2f2e6ed5f4c796d13aa1
// flow-typed version: <<STUB>>/is-stream_v^1.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-stream/index' {
  declare module.exports: $Exports<'is-stream'>;
}
declare module 'is-stream/index.js' {
  declare module.exports: $Exports<'is-stream'>;
}
