// flow-typed signature: 11035ad81664de83d25d89adadb9475b
// flow-typed version: <<STUB>>/jsdoc-to-markdown_v3.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdoc-to-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdoc-to-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsdoc-to-markdown/bin/cli' {
  declare module.exports: any;
}

declare module 'jsdoc-to-markdown/lib/cli-data' {
  declare module.exports: any;
}

declare module 'jsdoc-to-markdown/lib/dmd-options' {
  declare module.exports: any;
}

declare module 'jsdoc-to-markdown/lib/jsdoc-options' {
  declare module.exports: any;
}

declare module 'jsdoc-to-markdown/lib/jsdoc-to-markdown' {
  declare module.exports: any;
}

declare module 'jsdoc-to-markdown/test/async' {
  declare module.exports: any;
}

declare module 'jsdoc-to-markdown/test/cli' {
  declare module.exports: any;
}

declare module 'jsdoc-to-markdown/test/fixture/ignore' {
  declare module.exports: any;
}

declare module 'jsdoc-to-markdown/test/fixture/params' {
  declare module.exports: any;
}

declare module 'jsdoc-to-markdown/test/sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsdoc-to-markdown/bin/cli.js' {
  declare module.exports: $Exports<'jsdoc-to-markdown/bin/cli'>;
}
declare module 'jsdoc-to-markdown/lib/cli-data.js' {
  declare module.exports: $Exports<'jsdoc-to-markdown/lib/cli-data'>;
}
declare module 'jsdoc-to-markdown/lib/dmd-options.js' {
  declare module.exports: $Exports<'jsdoc-to-markdown/lib/dmd-options'>;
}
declare module 'jsdoc-to-markdown/lib/jsdoc-options.js' {
  declare module.exports: $Exports<'jsdoc-to-markdown/lib/jsdoc-options'>;
}
declare module 'jsdoc-to-markdown/lib/jsdoc-to-markdown.js' {
  declare module.exports: $Exports<'jsdoc-to-markdown/lib/jsdoc-to-markdown'>;
}
declare module 'jsdoc-to-markdown/test/async.js' {
  declare module.exports: $Exports<'jsdoc-to-markdown/test/async'>;
}
declare module 'jsdoc-to-markdown/test/cli.js' {
  declare module.exports: $Exports<'jsdoc-to-markdown/test/cli'>;
}
declare module 'jsdoc-to-markdown/test/fixture/ignore.js' {
  declare module.exports: $Exports<'jsdoc-to-markdown/test/fixture/ignore'>;
}
declare module 'jsdoc-to-markdown/test/fixture/params.js' {
  declare module.exports: $Exports<'jsdoc-to-markdown/test/fixture/params'>;
}
declare module 'jsdoc-to-markdown/test/sync.js' {
  declare module.exports: $Exports<'jsdoc-to-markdown/test/sync'>;
}
