// flow-typed signature: 20ef14dd2cc8c8b9151f5bdf9ccb7701
// flow-typed version: <<STUB>>/tunnel-agent_v^0.6.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tunnel-agent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tunnel-agent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'tunnel-agent/index' {
  declare module.exports: $Exports<'tunnel-agent'>;
}
declare module 'tunnel-agent/index.js' {
  declare module.exports: $Exports<'tunnel-agent'>;
}
